// src/containers/Info/Info.tsx
import * as React from 'react';
import { Authentication } from '../../components';
import history from '../../history/history';
import myGraphQLAxios from "../../utils/ApiRequest";

export namespace Info {
  export interface Props {

  }
  export interface State {
    id: string,
    name: string,
    email: string,
    phone: string,
    department: string,
    studentNumber: string
  }
}

export default class Info extends React.Component<Info.Props, Info.State> {
  constructor(props: Info.Props) {
    super(props);

    this.state = {
      id: '',
      name: '',
      email: '',
      phone: '',
      department: '',
      studentNumber: ''
    };
  }

  componentDidMount() {
    const token = localStorage.getItem('accessToken');

    if(token === null) {
      history.push('/404');
      return;
    }

    const data = `query {
      me {
        loginID,
        name,
        email,
        department,
        studentID,
        phoneNumber
      }
    }`;

    myGraphQLAxios(data, {
      authorization: true
    }).then((msg) => {
      // TODO: typing
      const data = msg.data;
      if('errors' in data) {
        if(data.errors[0].message === "ERR401") {
          history.push('/');
        } else {
          console.log("me API error -----");
          console.log(data);
        }
      } else {
        const data = msg.data.data.me;
        this.setState({
          id: data.loginID,
          name: data.name,
          email: data.email,
          department: data.department,
          studentNumber: data.studentID,
          phone: data.phoneNumber
        });
      }
    }).catch((msg) => {
      console.log("get member API error -----");
      console.log(msg);
    });
  }

  handleInfoModify(pw: string, email: string, phone: string) {
    if(pw.length !== 0) {
      if (pw.length < 8) {
        alert('비밀번호는 8자리 이상으로 설정해주세요.');
        return;
      }
      if (pw.length > 255) {
        alert('비밀번호가 너무 깁니다.');
        return;
      }
    }

    if(email.length === 0) {
      alert('이메일을 적어주세요.');
      return;
    }
    if(!(/^(([^<>()\[\]\\.,;:\s@']+(\.[^<>()\[\]\\.,;:\s@']+)*)|('.+'))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/).test(email.toLowerCase())) {
      alert('이메일 형식을 맞춰주세요');
      return;
    }
    if(email.length > 255) {
      alert('이메일이 너무 깁니다.');
      return;
    }
    if(!(/^\d{3}-\d{3,4}-\d{4}$/).test(phone)) {
      alert('휴대폰 번호를 다시 한번 확인해주세요.');
      return;
    }

    const data = `mutation {
      updateMember(MemberInput: {
        email: "${email}"
        phoneNumber: "${phone}"
        ${pw.length===0 ? '' : ('password: "' + pw + '"')}
      }) {
        uuid
      }
    }`;

    myGraphQLAxios(data, {
      authorization: true
    }).then((msg) => {
      // TODO: typing
      const data = msg.data;
      if('errors' in data) {
        console.log("update member API error -----");
        console.log(data);
      } else {
        alert("수정되었습니다.");
        history.push('/');
      }
    }).catch((msg) => {
      console.log("update member API error -----");
      console.log(msg);
    });
  }

  render(): JSX.Element {
    if(this.state.id === '')
      return null;

    return (
      <Authentication mode={3} handleInfoModify={this.handleInfoModify} loginInfo={this.state}/>
    );
  }
}

// src/views/Info.vue
<template>
  <div>
    <h1>내 정보</h1>
    <input-box label="아이디" type="text" disabled="true" :value="me.loginID"/>
    <input-box label="새 비밀번호" type="password"
               placeholder="8자리 이상" @change="me.password = $event"/>
    <input-box label="새 비밀번호 확인" type="password"
               placeholder="위에서 입력한 비밀번호와 동일하게"
               @change="me.pwConfirm = $event"/>
    <input-box label="이름" type="text" disabled="true" :value="me.name"/>
    <input-box label="이메일" type="text" placeholder="예) poolc.official@gmail.com"
               :value="me.email" @change="me.email = $event"/>
    <input-box label="전화번호" type="text" placeholder="예) 010-1234-5678"
               :value="me.phoneNumber" @change="me.phoneNumber = $event"/>
    <input-box label="소속학과" type="text"
               :value="me.department" @change="me.department = $event"/>
    <input-box label="학번" type="text" disabled="true" :value="me.studentID"/>
    <my-button @click="updateInfo">
      정보 수정
    </my-button>
  </div>
</template>

<script>
import InputBox from '@/components/InputBox.vue';
import MyButton from '@/components/MyButton.vue';

export default {
  name: 'Info',
  components: {
    MyButton,
    InputBox,
  },
  data() {
    return {
      me: {
        loginID: '',
        password: '',
        pwConfirm: '',
        name: '',
        email: '',
        department: '',
        studentID: '',
        phoneNumber: '',
      },
    };
  },
  created() {
    this.$api.request({
      data: `query {
        me {
          loginID, name, email, phoneNumber,
          department, studentID
        }
      }`,
    }).then((res) => {
      if ('errors' in res.data) {
        alert('다시 로그인 해주세요');
        this.$router.push('/');
      }
      this.me = res.data.data.me;
    });
  },
  methods: {
    updateInfo() {
      if (this.password && (this.password.length < 8 || this.password.length > 255)) {
        alert('비밀번호는 8자리 이상으로 255자리 이하로 설정해 주세요');
        return;
      }
      if (this.password !== this.pwConfirm) {
        alert('비밀번호와 비밀번호(확인)이 일치하지 않습니다');
        return;
      }
      if (this.email.length === 0) {
        alert('이메일을 적어주세요');
        return;
      }
      if (!(/^(([^<>()[\]\\.,;:\s@']+(\.[^<>()[\]\\.,;:\s@']+)*)|('.+'))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/).test(this.email.toLowerCase())) {
        alert('이메일 형식을 맞춰주세요');
        return;
      }
      if (this.email.length > 255) {
        alert('이메일이 너무 깁니다');
        return;
      }
      if (!(/^\d{3}-\d{3,4}-\d{4}$/).test(this.phoneNumber)) {
        alert('휴대폰 번호를 다시 한번 확인해주세요');
        return;
      }
      if (!this.department) {
        alert('소속학과를 적어주세요');
        return;
      }

      this.$api.request({
        data: `mutation {
          updateMember(MemberInput: {
            email: "${this.email}",
            phoneNumber: "${this.phoneNumber}",
            department: "${this.department}",
            ${this.password && `password: "${this.password}"`}
          }) {
            uuid
          }
        }`,
      }).then((res) => {
        if ('errors' in res.data) {
          alert('실패하였습니다. 회장에게 문의해 주세요');
          return;
        }

        alert('수정되었습니다');
      });
    },
  },
};
</script>

<style scoped>

</style>
